Stat svc request
akuniutka/java-explore-with-me-plus pull request #24
Opened 2024-11-04 15:10 UTC by AntonBelugin

Add request

2024-11-05 12:37 UTC, akuniutka requested changes
Основной вопрос: при отзыве пользователем своей заявки удалять её или переводить в статус CANCELED?

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestMapper.java
> +@UtilityClass
У аннотации `UntilityClass` непонятные перспективы, разработчики Lombok сомневаются, что она выйдет из экспериментального статуса:
_Current status: negative - Currently we feel this feature cannot move out of experimental status due to fundamental issues with non-star static imports._
https://projectlombok.org/features/experimental/UtilityClass
Я предлагаю сделать класс утилитным вручную: добавить `final` в определение класса + пустой приватный конструктор и `static` перед методом.

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestDto.java
> +        @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
По ТЗ здесь не требуется специальный формат даты, используется стандартный ISO-формат: 2022-09-06T21:10:05.432
Я предлагаю удалить эту аннотацию.

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/Request.java
> +    long id;
Мы с Дмитрием обсуждали, какой тип данных лучше использовать для идентификатора, и пришли к выводу, что класс-обёртка `Long` лучше примитива `long`: в PostgreSQL можно переопределить начальное значение для последовательности, используемой для id, и тогда значение равное 0 может соответствовать уже существующей заявке.

...An identity column, however, does not guarantee uniqueness. (A sequence normally returns unique values, but a sequence could be reset, or values could be inserted manually into the identity column, as discussed above.)...
https://www.postgresql.org/docs/current/ddl-identity-columns.html

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/Request.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Отличная идея! Нам действительно из события не понадобится ничего кроме его id 👍

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/Request.java
> +    @CreationTimestamp
Интересная идея. Правда, я пока не понимаю, как это можно замокать в тестах 🤔

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/Request.java
> +    @ManyToOne(fetch = FetchType.LAZY)
👍

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +@Slf4j
Здесь можно обойтись без этой аннотации, в классе-предке уже создаётся нужный логгер.

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +@RequestMapping("/users")
Можно вынести сюда общую часть эндпоинтов целиком:
```java
@RequestMapping("/users/{userId}/requests")
```

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +        Collection<RequestDto> response = requestService.getAllRequestByUserId(userId);
Предлагаю вставить перед этим строчку:
```java
logHttpRequest(httpRequest);
```
чтобы в логах было видно, что запрос дошёл до эндпоинта: когда что-то не работает, очень сложно понять — это проблема настройки сервера и запросы просто не доходят до приложения или же сломалось что-то в самом приложении.

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +    RequestDto save(@PathVariable final long userId, @RequestParam int eventId, final HttpServletRequest httpRequest) {
Здесь, видимо, опечатка и у переменной `userId` тип должен быть `long`?

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +        final RequestDto requestDto = requestService.create(userId, eventId);
Здесь тоже предлагаю вставить строчку:
```java
logHttpRequest(httpRequest);
```

2024-11-05 12:37 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Этой аннотации ведь не должно здесь быть, верно? По ТЗ мы возвращаем 200 (либо 404, если заявка не найдена).

2024-11-05 21:04 UTC, akuniutka requested changes

2024-11-05 21:04 UTC, akuniutka commented on main-service/src/main/java/ru/practicum/ewm/request/RequestServiceImpl.java
>          Request request = requestRepository.findById(requestId)
Я только сейчас понял, что мы не проверяем, что запрос на участие принадлежит данному пользователю. Давай добавим такую проверку? А то получается, что можно отозвать заявку любого другого пользователя 😱

2024-11-06 07:40 UTC, akuniutka submitted a review, later dismissed

2024-11-06 11:55 UTC, zolotyh-dk submitted a review, later dismissed

2024-11-06 20:53 UTC, akuniutka approved these changes

2024-11-07 02:43 UTC, zolotyh-dk approved these changes

2024-11-07 06:29 UTC, merged